name = input("hi, I am python! what is your name?")
print("Hello, " + name +  ", its nice to meet you!")
age = input ("How old are you?")
print("that's cool I'm 35!")
Grade = input ("What grade are you in?")
print("That,s cool!")